### ISSUE TITLE
enhancement: Add sound feedback when time is over.

### ISSUE THREAD

**Issue by viniciusgferreira** [lucaslopeslima/pomodoro_app#1]
It is good to reproduce a sound beep or similar to alert user at the end of pomodoros/breaks.

**Comment by lucaslopeslima** [comment]
> It is good to reproduce a sound beep or similar to alert user at the end of pomodoros/breaks.

Estranho que rodando internamente o alarme toca normalmente. Porém rodando na hospedagem o console retorna um erro de que o arquivo não foi encontrado:

GET file:///C:/.../GitHub/audio/alarm.wav net::ERR_FILE_NOT_FOUND
index.html:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.

Vou verificar o erro e corrigir. 
Obrigado pelo feedback!

**Comment by lucaslopeslima** [comment]
Fixed! =)
